export enum ErrorType {
  LOGIN_CANCELLED = "LOGIN_CANCELLED",
  GOOGLE_SIGN_IN_FAILED = "GOOGLE_SIGN_IN_FAILED",
  SUPABASE_SIGN_IN_FAILED = "SUPABASE_SIGN_IN_FAILED",
  FAILED_TO_GET_CURRENT_USER = "FAILED_TO_GET_CURRENT_USER",
  INVALID_FORM_DATA = "INVALID_FORM_DATA",
  NO_SHEET_SELECTED = "NO_SHEET_SELECTED",
  NO_GOOGLE_ACCESS_TOKEN = "NO_GOOGLE_ACCESS_TOKEN",
  FAILED_TO_FETCH_SHEETS = "FAILED_TO_FETCH_SHEETS",
  FAILED_TO_APPEND_TO_SHEET = "FAILED_TO_APPEND_TO_SHEET",
}
