export enum ErrorType {
  // Authentication errors
  LOGIN_CANCELLED = "LOGIN_CANCELLED",
  GOOGLE_SIGN_IN_FAILED = "GOOGLE_SIGN_IN_FAILED",
  SUPABASE_SIGN_IN_FAILED = "SUPABASE_SIGN_IN_FAILED",
  FAILED_TO_GET_CURRENT_USER = "FAILED_TO_GET_CURRENT_USER",
  NO_GOOGLE_ACCESS_TOKEN = "NO_GOOGLE_ACCESS_TOKEN",

  // Google Form errors
  INVALID_FORM_DATA = "INVALID_FORM_DATA",
  NO_SHEET_SELECTED = "NO_SHEET_SELECTED",
  FAILED_TO_FETCH_SHEETS = "FAILED_TO_FETCH_SHEETS",
  FAILED_TO_APPEND_TO_SHEET = "FAILED_TO_APPEND_TO_SHEET",
  SUBMISSION_IN_PROGRESS = "SUBMISSION_IN_PROGRESS",

  // Expense errors
  FAILED_TO_CREATE_EXPENSE = "FAILED_TO_CREATE_EXPENSE",
  FAILED_TO_FETCH_EXPENSES = "FAILED_TO_FETCH_EXPENSES",
  FAILED_TO_CREATE_SUB_AMOUNTS = "FAILED_TO_CREATE_SUB_AMOUNTS",
}
