export enum ErrorType {
  LOGIN_CANCELLED = "LOGIN_CANCELLED",
  GOOGLE_SIGN_IN_FAILED = "GOOGLE_SIGN_IN_FAILED",
  SUPABASE_SIGN_IN_FAILED = "SUPABASE_SIGN_IN_FAILED",
  FAILED_TO_GET_CURRENT_USER = "FAILED_TO_GET_CURRENT_USER",
}
